### PR TITLE
Pre-releasing v3.0.0-rc7

### PR DESCRIPTION
**Pull request by iky**
* porting a bug-fix from the stable release

### CODE REVIEW

**Comment by kooba** [comment]
So many good things in v3... can we cut the relase yet?

**Comment by mattbennett** [comment]
@kooba I want to release it along with a docs refresh. There's a lot which has changed and the current docs are quite out of date with 3.x. I'm working on an outline -- would be great to have a community effort filling in the details ;-)

**Comment by iky** [comment]
@kooba only a few doc entries missing! we should release soon.

**Comment by kooba** [comment]
Point me to the outline... I'll be happy to pitch in some docs.

**Comment by mattbennett** [comment]
@kooba https://www.notion.so/namekopython/Docs-Outline-64e72d7870d84292894d47cef61858b3

This is a fairly complete overhaul. We perhaps don’t need to do all of it before 3.0 but we need some of it at least (the intro, the restructure, and the "upgrading from 2.0" section)

**Pull request merged**
