### PR TITLE
Update rpc.py

### PR DESCRIPTION
**Pull request by 2XL**
may be ==> maybe

### CODE REVIEW

**Comment by davidszotten** [comment]
Hi,

thanks for noticing the sentence being off. however, i don't think the maybe(/may be) should be there at all, but rather read "... but uses a single reply queue ..."

**Comment by 2XL** [comment]
ok,
another Question:
following the docs
#helloworld.py
class TargetServiceName:
    name = "target_service_name"

    @rpc
    def method(self, name='method'):
        msg = "Hello, {}!".format(name)
        print(msg)
        return msg


#nameko_examples/client_rpc_helper.py
cluster_proxy = ClusterRpcProxy(config)
cluster_proxy = cluster_proxy.start()
cluster_proxy.target_service_name.method()
cluster_proxy.stop() 

`
Traceback (most recent call last):
  File "nameko_examples/client_rpc_helper.py", line 33, in <module>
    cluster_proxy.stop()
TypeError: 'ServiceProxy' object is not callable
`

what does this mean? 

Why am I getting this error?

**Comment by davidszotten** [comment]
looks like another bug in the docs. the problem is variable re-use `cluster_proxy = cluster_proxy.start()`

the `stop` should be called on the first object, but it's replaced by the result of `start()`.

the best option is probably to use the context manager version (though we should fix the docs)

**Comment by 2XL** [comment]
ok solved
```python
#################################################################
# CLUSTER_PROXY
#
# with ClusterRpcProxy(config) as cluster_proxy_raw:
#     cluster_proxy_raw.greeting_service.hello()

cluster_proxy = ClusterRpcProxy(config)
cluster_proxy_connector = cluster_proxy.start()
cluster_proxy_connector.target_service_name.method()
cluster_proxy.stop() 
```

Thanks David!, appreciate your support.

**Pull request closed without merging**
