### PR TITLE
Pytest upgrade

### PR DESCRIPTION
**Pull request by mattbennett**

### CODE REVIEW

**Comment by elicaciocdefarias** [comment]
Hi dear,

when will is PR be applied?

**Comment by mattbennett** [comment]
Hi @elicaciocdefarias. 

I opened this as an investigation into the bug reported in #725. I don't see any reason it can't be merged.

But since this mostly affects Nameko's own test suite, what is your reason for wanting it merged?

**Comment by elicaciocdefarias** [comment]
Hi @mattbennett,

The same as reported here #725.

**Comment by mattbennett** [comment]
This PR isn't a fix for #725, and merging it wouldn't prevent the problem reported there as far as I can tell.

Perhaps @vlcinsky's [comment](https://github.com/nameko/nameko/issues/725#issuecomment-956228468) on that issue might be useful?

**Comment by vlcinsky** [comment]
It is possible that the #725 is bogus (as there are problems to reproduce the problem).

Anyway, upgrading pytest is highly desirable as the old pytest version will fail with python 3.10.

Personally I do not see any reason not merging this PR now.

**Comment by mattbennett** [comment]
Thanks for your opinion @vlcinsky. I will merge this :)

**Comment by elicaciocdefarias** [comment]
@mattbennett , @vlcinsky , thanks.

**Pull request merged**
